version: '3.9'

services:
  vania:
    build: .
    image: vania/app:latest
    container_name: vania
    restart: always
    volumes:
      - app:/app
      - ./public:/public
      - ./storage:/storage
    ports:
      - "8000:8000"

volumes:
  app: